name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      buildAll:
        description: 'Build all directories regardless of updates'
        required: true
        default: 'true'
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push updated container images
        run: |
            ignore_dirs=(".git" ".github" "NOT-MANTAINED" ".")
            dirs=$(find . -maxdepth 1 -type d | sed 's|^./||')
            for dir in $dirs; do
              echo "Processing directory: $dir"
              dir_name=$(basename "$dir")
              if [[ " ${ignore_dirs[@]} " =~ " ${dir_name} " ]]; then
                echo "Ignoring directory: $dir_name"
                continue
              fi
              if [ -d "$dir" ]; then
                if [ -f "$dir/version" ]; then
                  version=$(cat "$dir/version")
                  echo "Found version file in $dir. Using version: $version"
                else
                  version="latest"
                  echo "No version file found in $dir. Using default version: $version"
                fi
                docker build -t ghcr.io/${{ github.repository }}/${dir_name}:$version "$dir"
                docker push ghcr.io/${{ github.repository }}/${dir_name}:$version
              fi
            done
